export const PRESENTATION_PROFILES={
 talking_head:{label:'The Talking Head',keywords:['talking head','direct eye contact','facetime','medium close-up'],purpose:'creator speaks directly to camera with product cutaways',storyBias:['hook','context','product mention','proof detail','CTA'],visualRules:['medium close-up','eye contact','hand gestures','product near lens'],motionRules:['natural head movement','hand gestures','product lift'],voBias:'conversational and direct'},
 pov:{label:'The POV',keywords:['first-person','point of view','hands interacting'],purpose:'audience sees product from user perspective',storyBias:['situation','hand interaction','product use','reaction'],visualRules:['first-person framing','hands visible','eye-level camera'],motionRules:['hand continuity','real grip/use','no floating product'],voBias:'short observational narration'},
 asmr_lofi:{label:'ASMR / Lo-Fi',keywords:['asmr','lo-fi','no talking','sound-heavy','macro'],purpose:'sensory product experience with minimal VO',storyBias:['texture','sound','close-up process','satisfying result'],visualRules:['extreme close-up','slow movement','texture detail'],motionRules:['slow tactile action','tapping/opening/pouring/clicking'],voBias:'minimal sensory caption-like'},
 grwm:{label:'GRWM',keywords:['grwm','get ready with me','multitasking','mirror'],purpose:'product appears naturally in getting-ready routine',storyBias:['routine start','product use','fit/finish','ready moment'],visualRules:['mirror movement','casual outfit','vanity/table'],motionRules:['apply/wear/adjust product while moving'],voBias:'personal routine narration'},
 raw_unboxing:{label:'Raw Unboxing',keywords:['unboxing','tearing package','peeling off plastic','initial reaction'],purpose:'first impression and tactile reveal',storyBias:['package reveal','open','detail','try/use','reaction'],visualRules:['package opening','contents shown','natural light'],motionRules:['tear/open/peel/lift product'],voBias:'curious first impression'},
 problem_solution:{label:'The Problem-Solution',keywords:['problem-solution','frustrated','problem situation','relaxed face'],purpose:'clear problem, product as solution, believable payoff',storyBias:['problem','why it matters','product enters','proof','CTA'],visualRules:['problem first','product hero','result/reaction'],motionRules:['show friction then product solving it'],voBias:'clear and benefit-aware'},
 cinematic_broll:{label:'Cinematic B-Roll',keywords:['cinematic b-roll','slow motion','rack focus','panning'],purpose:'premium visual storytelling with minimal talking',storyBias:['mood','product reveal','detail','hero'],visualRules:['smooth movement','rack focus','aesthetic light'],motionRules:['slow controlled motion','hero reveal'],voBias:'polished and sparse'},
 next_door:{label:'The Girl/Boy Next Door',keywords:['girl/boy next door','sitting on floor','casual spill'],purpose:'friendly relatable creator casually showing product',storyBias:['casual confession','product detail','small proof','soft recommendation'],visualRules:['informal posture','product close to lens','smiling'],motionRules:['casual product lift','micro reactions'],voBias:'warm and friend-like'},
 testing_demo:{label:'Testing / Demo',keywords:['testing','demo','live application','real-time results','efficacy'],purpose:'show product tested directly with visible proof',storyBias:['problem','demo action','proof detail','reaction','CTA'],visualRules:['real-time use','close-up result','human reaction','no vague stock footage'],motionRules:['one clear action beat per scene','physical proof','result reaction'],voBias:'practical and specific'},
 whats_in_bag_car:{label:"What's In My Bag/Car",keywords:['bag','car','compartment','daily carry','in the wild'],purpose:'product appears as useful daily carry',storyBias:['daily situation','discover product','why carried','use moment'],visualRules:['bag/car compartment','casual discovery','daily proof'],motionRules:['pull product out','place back','use in context'],voBias:'casual daily-life'},
 green_screen_reaction:{label:'Green Screen Reaction',keywords:['green screen','pointing','review','reacting'],purpose:'creator reacts to claim/review/screenshot safely',storyBias:['claim/context','reaction','explanation','product detail'],visualRules:['creator corner framing','background card feel without fake text'],motionRules:['pointing gesture','reaction expression','product cutaway'],voBias:'reactive but claim-safe'},
 ditl:{label:'Day in the Life',keywords:['day in the life','ditl','throughout the day','montage'],purpose:'product appears naturally across daily moments',storyBias:['morning','midday use','afternoon proof','end reflection'],visualRules:['multiple daily settings','lifestyle integration','wide and close-up mix'],motionRules:['natural transitions','carry/use/reuse product'],voBias:'diary-like narrative'}
};
export function inferPresentationType(txt=''){const t=String(txt).toLowerCase(); for(const [k,p] of Object.entries(PRESENTATION_PROFILES)){ if(t.includes(p.label.toLowerCase())||p.keywords.some(x=>t.includes(x))) return k;} return 'talking_head';}
export function getPresentationProfile(type='talking_head'){return PRESENTATION_PROFILES[type]||PRESENTATION_PROFILES.talking_head;}
