// ==================== APPLICATION STATE ====================
export const state = {
    currentStep: -1,
    contentStyle: 'IKLAN',
    uploadedFiles: { char: null, prod: [null, null, null, null] },
    selectedCategory: 'FASHION',
    selectedStyle: 'LIFESTYLE',
    selectedLang: 'ID',
    productName: 'Indomie Goreng',
    productDescription: '',
    ugcBackground: 'Scandinavian-Japanese fusion, beige limewash wall, light oak wood slats, pampas grass in ceramic vase, linen textures, clean space.',
    presentationKeywords: 'Direct eye contact, framing: medium close-up, hand gestures, expressive facial expressions, talking to camera, FaceTime-style framing.',
    presentationType: 'talking_head',
    selectedTone: 'jaksel',

    speakingStyle: 'casual_indonesia',
    voicePersona: 'reviewer',
    voiceEnergy: 'medium',
    slangLevel: 'light',
    ctaStyle: 'soft_cta',
    voLength: 'short',
    lensStyle: 'portrait',
    targetPlatform: 'multi_platform',
    contentGoal: 'viral_relatable',
    targetAudience: '',
    contentDuration: '15s',
    sceneCount: 'auto',
    hookType: 'auto',
    ctaType: 'soft_recommendation',
    productVisibility: 'balanced',
    cameraStyle: 'handheld_phone',

    characterMode: 'auto',
    characterGender: 'auto',
    characterAgeRange: 'young_adult',
    characterLock: 'strong',
    outfitLock: 'same_outfit',
    characterNotes: '',

    backgroundMode: 'fixed',
    backgroundLock: 'strong',
    backgroundLabel: 'Main Background',
    backgroundDescription: '',
    lightingLock: 'same_mood',
    continuityStrength: 'strong',

    productRef1Role: 'main_packaging',
    productRef2Role: 'serving_result',
    productRef3Role: 'texture_detail',
    productRef4Role: 'bundle',
    productRef1Instruction: '',
    productRef2Instruction: '',
    productRef3Instruction: '',
    productRef4Instruction: '',

    scene1ProductRefs: 'auto',
    scene2ProductRefs: 'auto',
    scene3ProductRefs: 'auto',
    scene4ProductRefs: 'auto',
    scene5ProductRefs: 'auto',
    scene6ProductRefs: 'auto',
    scene7ProductRefs: 'auto',
    scene8ProductRefs: 'auto',
    scene9ProductRefs: 'auto',
    scene10ProductRefs: 'auto',

    scene1ProductVisibility: 'subtle',
    scene2ProductVisibility: 'balanced',
    scene3ProductVisibility: 'strong',
    scene4ProductVisibility: 'strong',
    scene5ProductVisibility: 'balanced',
    scene6ProductVisibility: 'balanced',
    scene7ProductVisibility: 'strong',
    scene8ProductVisibility: 'balanced',
    scene9ProductVisibility: 'hero',
    scene10ProductVisibility: 'strong',

    scene1ProductRole: '',
    scene2ProductRole: '',
    scene3ProductRole: '',
    scene4ProductRole: '',
    scene5ProductRole: '',
    scene6ProductRole: '',
    scene7ProductRole: '',
    scene8ProductRole: '',
    scene9ProductRole: '',
    scene10ProductRole: '',

    scene1ProductInstruction: '',
    scene2ProductInstruction: '',
    scene3ProductInstruction: '',
    scene4ProductInstruction: '',
    scene5ProductInstruction: '',
    scene6ProductInstruction: '',
    scene7ProductInstruction: '',
    scene8ProductInstruction: '',
    scene9ProductInstruction: '',
    scene10ProductInstruction: '',

    mainBenefit: '',
    painPoint: '',
    usageMoment: '',
    offer: '',
    claimSafety: 'safe_general',
    selectedVideoModel: 'veo',
    selectedImageModel: 'banana_pro',
    customNegativePrompt: '',
    apiKey: '',
    generatedData: null,
    currentProjectName: ''
};

export function updateState(partial) {
    Object.assign(state, partial);
}
